-- Kayan University (جامعة كيان), the Armed Forces' first civilian university,
-- added 2026-10-10. Fees and faculty minimums from the client sheet
-- "مصروفات_الجامعات_المصرية_2026_2027 (6).xlsx"; listed as PRIVATE per the
-- client. Location, faculties, program lists, durations and admission tests
-- from press coverage of the October 2026 intake (Al-Ahram Weekly, Al-Ahram,
-- Akhbar El Yom, filgamaa.com). No logo/photos published yet. Safe to re-run.

BEGIN;

INSERT INTO "University" (id, name, "nameAr", slug, type, country, "countryAr", city, "cityAr", description, "descriptionAr", "establishedYear", "addressLine", "addressLineAr", "publishedAt", "updatedAt")
VALUES ('univ_13e2c1693c294ccab007', 'Kayan University', 'جامعة كيان', 'kayan-university', 'PRIVATE', 'Egypt', 'مصر', 'New Administrative Capital', 'العاصمة الإدارية الجديدة', 'Kayan University is the first civilian university launched by the Egyptian Armed Forces, established under the law creating Kayan University of Applied Sciences. It is based inside the Egyptian Military Academy in the New Administrative Capital and takes its first intake in October 2026. It opens with six faculties: medicine, dentistry, pharmacy, physical therapy, engineering, and computers and artificial intelligence, supported by an integrated university hospital, a medical simulation center and a physical therapy and rehabilitation center. Admission is open to holders of Thanaweya Amma, Al-Azhar and equivalent certificates, and includes fitness, psychological and aptitude tests and a personal interview.', 'جامعة كيان هي أول جامعة مدنية تطلقها القوات المسلحة المصرية، وأُنشئت بموجب قانون إنشاء جامعة كيان للعلوم التطبيقية. تقع داخل الأكاديمية العسكرية بالعاصمة الإدارية الجديدة، وتستقبل أول دفعة من طلابها في أكتوبر 2026. تبدأ بست كليات هي الطب وطب الأسنان والصيدلة والعلاج الطبيعي والهندسة والحاسبات والذكاء الاصطناعي، مع مستشفى جامعي متكامل ومركز للمحاكاة الطبية ومركز للعلاج الطبيعي والتأهيل. يُقبل بها حاصلو الثانوية العامة والأزهرية والشهادات المعادلة، ويشمل القبول اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات والمقابلة الشخصية.', 2026, 'Egyptian Military Academy, New Administrative Capital', 'الأكاديمية العسكرية، العاصمة الإدارية الجديدة', now(), now())
ON CONFLICT (slug) DO NOTHING;

INSERT INTO "Faculty" (id, "universityId", name, "nameAr", slug, "sortOrder", "updatedAt")
SELECT 'fac_2c213172c09e44d7b7b5', u.id, 'Faculty of Medicine', 'كلية الطب', 'faculty-of-medicine', 0, now() FROM "University" u WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_30928628ce804e52a691', u.id, f.id, 'Medicine', 'الطب البشري', 'medicine', 'BACHELOR', 'medicine', 84, '7 years (5 years of study + 2-year internship)', '7 سنوات (5 سنوات دراسة + سنتان امتياز)', 245000, 'YEAR', 'EGP', 90, 'Admission: minimum 90% (science stream), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 90% (شعبة علمي علوم)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-medicine' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Faculty" (id, "universityId", name, "nameAr", slug, "sortOrder", "updatedAt")
SELECT 'fac_946df4b2c57545829e1e', u.id, 'Faculty of Dentistry', 'كلية طب الفم والأسنان', 'faculty-of-dentistry', 1, now() FROM "University" u WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_c368797e61d843b09364', u.id, f.id, 'Dentistry', 'طب الفم والأسنان', 'dentistry', 'BACHELOR', 'dentistry', 72, '6 years (5 years of study + 1-year internship)', '6 سنوات (5 سنوات دراسة + سنة امتياز)', 242500, 'YEAR', 'EGP', 89, 'Admission: minimum 89% (science stream), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 89% (شعبة علمي علوم)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-dentistry' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Faculty" (id, "universityId", name, "nameAr", slug, "sortOrder", "updatedAt")
SELECT 'fac_c19816c17dc147aeba73', u.id, 'Faculty of Physical Therapy', 'كلية العلاج الطبيعي', 'faculty-of-physical-therapy', 2, now() FROM "University" u WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_15b9a539dc7441438016', u.id, f.id, 'Physical Therapy', 'العلاج الطبيعي', 'physical-therapy', 'BACHELOR', 'physical_therapy', 72, '6 years (5 years of study + 1-year internship)', '6 سنوات (5 سنوات دراسة + سنة امتياز)', 205500, 'YEAR', 'EGP', 88, 'Admission: minimum 88% (science stream), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 88% (شعبة علمي علوم)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-physical-therapy' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Faculty" (id, "universityId", name, "nameAr", slug, "sortOrder", "updatedAt")
SELECT 'fac_3f1a60b1e4bd4bd5abef', u.id, 'Faculty of Pharmacy', 'كلية الصيدلة', 'faculty-of-pharmacy', 3, now() FROM "University" u WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_200d9c8a7a5544378f37', u.id, f.id, 'Pharmacy', 'الصيدلة', 'pharmacy', 'BACHELOR', 'pharmacy', 72, '6 years (5 years of study + 1-year internship)', '6 سنوات (5 سنوات دراسة + سنة امتياز)', 220500, 'YEAR', 'EGP', 87, 'Admission: minimum 87% (science stream), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 87% (شعبة علمي علوم)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-pharmacy' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Faculty" (id, "universityId", name, "nameAr", slug, "sortOrder", "updatedAt")
SELECT 'fac_eacc9e9a3a3f4765abf7', u.id, 'Faculty of Engineering', 'كلية الهندسة', 'faculty-of-engineering', 4, now() FROM "University" u WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_f5b227fb503b4754a94b', u.id, f.id, 'Electronics & Communications Engineering', 'هندسة الإلكترونيات والاتصالات', 'electronics-and-communications-engineering', 'BACHELOR', 'engineering', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 200000, 'YEAR', 'EGP', 85, 'Admission: minimum 85% (mathematics stream), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 85% (شعبة علمي رياضة)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-engineering' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_2eb91f11cab24d63ba0e', u.id, f.id, 'Electrical Power & Energy Engineering', 'هندسة القوى الكهربية والطاقة', 'electrical-power-and-energy-engineering', 'BACHELOR', 'engineering', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 200000, 'YEAR', 'EGP', 85, 'Admission: minimum 85% (mathematics stream), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 85% (شعبة علمي رياضة)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-engineering' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_de0fd2076221453a9fc7', u.id, f.id, 'Biomedical Engineering', 'الهندسة الطبية', 'biomedical-engineering', 'BACHELOR', 'engineering', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 200000, 'YEAR', 'EGP', 85, 'Admission: minimum 85% (mathematics stream), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 85% (شعبة علمي رياضة)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-engineering' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_738e41cb7ef947a3b5b2', u.id, f.id, 'Mechanical Power & Energy Engineering', 'هندسة القوى الميكانيكية والطاقة', 'mechanical-power-and-energy-engineering', 'BACHELOR', 'engineering', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 200000, 'YEAR', 'EGP', 85, 'Admission: minimum 85% (mathematics stream), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 85% (شعبة علمي رياضة)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-engineering' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_68a53c6b64e24e6dbc18', u.id, f.id, 'Mechatronics Engineering', 'هندسة الميكاترونكس', 'mechatronics-engineering', 'BACHELOR', 'engineering', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 200000, 'YEAR', 'EGP', 85, 'Admission: minimum 85% (mathematics stream), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 85% (شعبة علمي رياضة)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-engineering' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_45abefa06f4741938496', u.id, f.id, 'Design & Manufacturing Engineering', 'هندسة التصميم والتصنيع', 'design-and-manufacturing-engineering', 'BACHELOR', 'engineering', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 200000, 'YEAR', 'EGP', 85, 'Admission: minimum 85% (mathematics stream), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 85% (شعبة علمي رياضة)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-engineering' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Faculty" (id, "universityId", name, "nameAr", slug, "sortOrder", "updatedAt")
SELECT 'fac_35e7280bb7dd4be38e2e', u.id, 'Faculty of Computers & Artificial Intelligence', 'كلية الحاسبات والذكاء الاصطناعي', 'faculty-of-computers-and-artificial-intelligence', 5, now() FROM "University" u WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_3bf45650f93c41e1a35e', u.id, f.id, 'Computer Science', 'علوم الحاسب', 'computer-science', 'BACHELOR', 'computer_science', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 181000, 'YEAR', 'EGP', 80, 'Admission: minimum 80% (science section), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 80% (الشعبة العلمية)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-computers-and-artificial-intelligence' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_5f270b7eaa214958b892', u.id, f.id, 'Software Engineering', 'البرمجيات', 'software-engineering', 'BACHELOR', 'computer_science', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 181000, 'YEAR', 'EGP', 80, 'Admission: minimum 80% (science section), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 80% (الشعبة العلمية)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-computers-and-artificial-intelligence' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_e7e89047111e45e8aef6', u.id, f.id, 'Cybersecurity', 'الأمن السيبراني', 'cybersecurity', 'BACHELOR', 'computer_science', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 181000, 'YEAR', 'EGP', 80, 'Admission: minimum 80% (science section), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 80% (الشعبة العلمية)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-computers-and-artificial-intelligence' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_089fd2fcc7c841018ea7', u.id, f.id, 'Data Science', 'علوم البيانات', 'data-science', 'BACHELOR', 'computer_science', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 181000, 'YEAR', 'EGP', 80, 'Admission: minimum 80% (science section), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 80% (الشعبة العلمية)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-computers-and-artificial-intelligence' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;
INSERT INTO "Program" (id, "universityId", "facultyId", name, "nameAr", slug, "studyLevel", "fieldOfStudy", "durationMonths", "durationLabel", "durationLabelAr", "tuitionFee", "tuitionPeriod", currency, "minGradePercent", description, "descriptionAr", tags, "isPublished", "updatedAt")
SELECT 'prog_f2098ff4f99143cdba0f', u.id, f.id, 'Intelligent Systems & Robotics', 'الأنظمة الذكية والروبوتات', 'intelligent-systems-and-robotics', 'BACHELOR', 'artificial_intelligence', 48, '4 years (credit hours)', '4 سنوات (نظام الساعات المعتمدة)', 181000, 'YEAR', 'EGP', 80, 'Admission: minimum 80% (science section), plus fitness, psychological and aptitude tests (English, computing, chemistry, biology and an intelligence test) and a personal interview. Applicants must be no older than 21 on 1 November 2026.', 'القبول: حد أدنى 80% (الشعبة العلمية)، واجتياز اختبارات اللياقة البدنية والاختبارات النفسية واختبارات القدرات (اللغة الإنجليزية والحاسب والكيمياء والأحياء واختبار الذكاء) والمقابلة الشخصية. ويُشترط ألا يزيد سن المتقدم على 21 عامًا في 1 نوفمبر 2026.', '{}', true, now()
FROM "University" u JOIN "Faculty" f ON f."universityId" = u.id AND f.slug = 'faculty-of-computers-and-artificial-intelligence' WHERE u.slug = 'kayan-university'
ON CONFLICT ("universityId", slug) DO NOTHING;

COMMIT;
