-- University descriptions, rewritten for all 51 universities from the
-- client-supplied Arabic sheet ("وصف الجامعات.xlsx", 2026-10-08). The Arabic
-- is the sheet's text with only markdown markers and three missing spaces
-- fixed; the English is a translation of it, with no facts added.

BEGIN;

UPDATE "University" SET description = 'The Egyptian Chinese University is a private university in Egypt offering education that combines academic study with practical application, drawing on Chinese expertise and experience in education and technology. The university focuses on preparing students for the job market through hands-on training and the development of professional skills. Its programs span a range of fields, including engineering, information technology, economics and physical therapy, among others. It also emphasizes innovation and entrepreneurship, providing a learning environment that helps students build their skills and get ready for the demands of the job market.',
  "descriptionAr" = 'الجامعة المصرية الصينية هي جامعة خاصة في مصر تقدم تعليما يجمع بين الدراسة الأكاديمية والتطبيق العملي، مع الاستفادة من الخبرات والتجربة الصينية في مجالات التعليم والتكنولوجيا. تهتم الجامعة بتأهيل الطلاب لسوق العمل من خلال التدريب العملي وتنمية المهارات المهنية. وتضم برامج دراسية في مجالات متنوعة، من بينها الهندسة، وتكنولوجيا المعلومات، والاقتصاد، والعلاج الطبيعي، وغيرها. كما تركز على الابتكار وريادة الأعمال، وتوفير بيئة تعليمية تساعد الطلاب على تطوير مهاراتهم والاستعداد لمتطلبات سوق العمل.'
WHERE slug = 'egyptian-chinese-university';

UPDATE "University" SET description = 'May University in Cairo is a private university founded in 2019 in 15th of May City, Cairo. It offers academic programs across a range of fields, including engineering; politics, economics and business administration; physical therapy; nursing; and technology. The university focuses on combining academic knowledge with practical application, developing critical and creative thinking skills, and linking education to the needs of the job market. It also provides a learning environment built on modern technology and hands-on training, alongside student activities and international academic cooperation.',
  "descriptionAr" = 'جامعة مايو بالقاهرة هي جامعة خاصة تأسست عام 2019 وتقع في مدينة 15 مايو بالقاهرة. تقدم الجامعة برامج أكاديمية في مجالات متنوعة تشمل الهندسة، والسياسة والاقتصاد وإدارة الأعمال، والعلاج الطبيعي، والتمريض، والتكنولوجيا. وتركز الجامعة على الجمع بين المعرفة الأكاديمية والتطبيق العملي، مع الاهتمام بتنمية مهارات التفكير النقدي والإبداعي وربط التعليم باحتياجات سوق العمل. كما توفر بيئة تعليمية تعتمد على التقنيات الحديثة والتدريب العملي، إلى جانب الأنشطة الطلابية والتعاون الأكاديمي الدولي.'
WHERE slug = 'may-university-in-cairo';

UPDATE "University" SET description = 'The Egyptian Russian University is a private university founded in 2006 in Badr City, Cairo. It offers academic programs across a range of fields, including engineering, pharmacy, dentistry, management, and computers and information technology. The university combines academic study with practical application, with a focus on building skills and linking education to the needs of the job market. It is also distinguished by its academic cooperation with a number of Russian universities, giving students opportunities to study and train in Russia through some programs and agreements. The university also places emphasis on innovation, student activities and professional development.',
  "descriptionAr" = 'الجامعة المصرية الروسية هي جامعة خاصة تأسست عام 2006 وتقع في مدينة بدر بالقاهرة. تقدم الجامعة برامج أكاديمية في مجالات متنوعة تشمل الهندسة، والصيدلة، وطب الفم والأسنان، والإدارة، وتكنولوجيا المعلومات والحاسبات. وتعتمد الجامعة على الجمع بين الدراسة الأكاديمية والتطبيق العملي، مع اهتمام بتنمية المهارات وربط التعليم باحتياجات سوق العمل. كما تتميز بالتعاون الأكاديمي مع عدد من الجامعات الروسية، وتوفر لطلابها فرصا للدراسة والتدريب في روسيا ضمن بعض البرامج والاتفاقيات. وتهتم الجامعة أيضا بالابتكار والأنشطة الطلابية والتطوير المهني.'
WHERE slug = 'egyptian-russian-university';

UPDATE "University" SET description = 'Hertfordshire University Egypt offers academic programs in partnership with the UK''s University of Hertfordshire, giving students a learning experience based on the British model of study. It offers programs in business administration, computer science and mechanical engineering, combining academic study with practical application. The programs focus on developing scientific and professional skills and preparing students for the demands of the job market. The university also provides a learning environment with labs and facilities that support hands-on training, and students can earn a degree linked to the University of Hertfordshire in the UK.',
  "descriptionAr" = 'جامعة هيرتفوردشاير في مصر هي جامعة تقدم برامج أكاديمية بالتعاون مع جامعة هيرتفوردشاير البريطانية، وتوفر للطلاب تجربة تعليمية تعتمد على النموذج البريطاني في الدراسة. تضم الجامعة برامج في مجالات إدارة الأعمال، وعلوم الكمبيوتر، والهندسة الميكانيكية، مع الجمع بين الدراسة الأكاديمية والتطبيق العملي. وتركز البرامج على تنمية المهارات العلمية والمهنية وإعداد الطلاب لمتطلبات سوق العمل. كما توفر الجامعة بيئة تعليمية تضم معامل ومرافق تساعد على التدريب العملي، مع إتاحة الحصول على شهادة مرتبطة بجامعة هيرتفوردشاير البريطانية.'
WHERE slug = 'hertfordshire-university-egypt';

UPDATE "University" SET description = 'The German University in Cairo is a private university in Egypt offering education based on the German model, with a focus on academic study, practical application and scientific research. Its programs span a range of fields, including engineering, information technology, computer science, management, pharmacy and biotechnology, design, and dentistry. It provides a learning environment with specialized labs and facilities, along with opportunities for training and academic exchange. Students also study German as part of their programs, with opportunities to study and do research in Germany at certain stages and in certain programs.',
  "descriptionAr" = 'الجامعة الألمانية بالقاهرة هي جامعة خاصة في مصر تقدم تعليما يعتمد على النموذج الألماني، مع التركيز على الدراسة الأكاديمية والتطبيق العملي والبحث العلمي. تضم الجامعة برامج في مجالات متنوعة تشمل الهندسة، وتكنولوجيا المعلومات، وعلوم الحاسب، والإدارة، والصيدلة والتكنولوجيا الحيوية، والتصميم، وطب الأسنان. وتوفر بيئة تعليمية تضم معامل ومرافق متخصصة، إلى جانب فرص للتدريب والتبادل الأكاديمي. كما يدرس الطلاب اللغة الألمانية ضمن برامجهم، مع إتاحة فرص للدراسة والبحث في ألمانيا في بعض المراحل والبرامج.'
WHERE slug = 'german-university-in-cairo-guc';

UPDATE "University" SET description = 'New Giza University is a private university on the Cairo-Alexandria Desert Road, near the Pyramids. Teaching began in 2016, and it offers academic programs across a range of fields, including medicine, dentistry, pharmacy, engineering, information technology, business administration and finance, economics and politics, and arts and design. The university focuses on combining academic knowledge with practical application, and has academic cooperation with international universities and educational institutions. It also provides a learning environment with specialized labs and facilities and spaces for activities and study, with an emphasis on scientific research and professional skills development.',
  "descriptionAr" = 'جامعة الجيزة الجديدة هي جامعة خاصة تقع على طريق القاهرة - الإسكندرية الصحراوي بالقرب من منطقة الأهرامات. بدأت الدراسة بها عام 2016، وتقدم برامج أكاديمية في مجالات متنوعة تشمل الطب، وطب الأسنان، والصيدلة، والهندسة، وتكنولوجيا المعلومات، وإدارة الأعمال والمالية، والاقتصاد والسياسة، والفنون والتصميم. وتركز الجامعة على الجمع بين المعرفة الأكاديمية والتطبيق العملي، مع وجود تعاون أكاديمي مع جامعات ومؤسسات تعليمية دولية. كما توفر الجامعة بيئة تعليمية تضم معامل ومرافق متخصصة ومساحات للأنشطة والدراسة، مع اهتمام بالبحث العلمي وتنمية المهارات المهنية.'
WHERE slug = 'new-giza-university';

UPDATE "University" SET description = 'Badr University in Assiut is a private university in Nasser City, west of Assiut, offering a variety of academic programs across medical, scientific and humanities fields. Its faculties and programs include dentistry, pharmacy, physical therapy, nursing, veterinary medicine, artificial intelligence and data science, biotechnology, health sciences, languages and translation, law, business administration, and applied arts. The university focuses on combining academic study with practical application, with an emphasis on training, skills development and aligning programs with the needs of the job market, alongside student activities and services.',
  "descriptionAr" = 'جامعة بدر بأسيوط هي جامعة خاصة تقع في مدينة ناصر غرب أسيوط، وتقدم برامج أكاديمية متنوعة في عدد من المجالات الطبية والعلمية والإنسانية. تضم الجامعة كليات وبرامج في طب الفم والأسنان، والصيدلة، والعلاج الطبيعي، والتمريض، والطب البيطري، والذكاء الاصطناعي وعلوم البيانات، والتكنولوجيا الحيوية، والعلوم الصحية، واللغات والترجمة، والقانون، وإدارة الأعمال، والفنون التطبيقية. وتركز الجامعة على الجمع بين الدراسة الأكاديمية والتطبيق العملي، مع الاهتمام بالتدريب وتنمية المهارات وربط البرامج باحتياجات سوق العمل، إلى جانب الأنشطة والخدمات الطلابية.'
WHERE slug = 'badr-university-in-assiut';

UPDATE "University" SET description = 'Delta University for Science and Technology is a private university founded in 2007 in Gamasa, Dakahlia Governorate. It offers academic programs across a range of fields, including medicine, dentistry, pharmacy, physical therapy, health sciences, engineering, artificial intelligence, business administration, arts, nursing, and veterinary medicine. The university focuses on combining academic study with practical application, providing labs, training facilities and a university hospital to serve its medical programs. It also values academic cooperation and hands-on training, and offers students opportunities to take part in international activities and educational experiences.',
  "descriptionAr" = 'جامعة الدلتا للعلوم والتكنولوجيا هي جامعة خاصة تأسست عام 2007 وتقع بمدينة جمصة في محافظة الدقهلية. تقدم الجامعة برامج أكاديمية في مجالات متنوعة تشمل الطب، وطب الفم والأسنان، والصيدلة، والعلاج الطبيعي، والعلوم الصحية، والهندسة، والذكاء الاصطناعي، وإدارة الأعمال، والآداب، والتمريض، والطب البيطري. وتركز الجامعة على الجمع بين الدراسة الأكاديمية والتطبيق العملي، مع توفير معامل ومنشآت تدريبية ومستشفى جامعي لخدمة البرامج الطبية. كما تهتم بالتعاون الأكاديمي والتدريب العملي، وتوفر لطلابها فرصا للمشاركة في الأنشطة والتجارب التعليمية الدولية.'
WHERE slug = 'delta-university-for-science-and-technology';

UPDATE "University" SET description = 'Merit University is a private university founded in 2019 in New Sohag City, serving students in Upper Egypt through academic programs in medical, scientific and technological fields. Its faculties include medicine, physical therapy, pharmacy and biotechnology, and its programs are taught in English. Study combines academic work with practical application, with specialized labs and opportunities for training and scientific research. The university also values student activities and skills development, and provides a learning environment aimed at preparing students for the demands of the job market.',
  "descriptionAr" = 'جامعة ميريت هي جامعة خاصة تأسست عام 2019 وتقع في مدينة سوهاج الجديدة، وتخدم طلاب صعيد مصر من خلال برامج أكاديمية في المجالات الطبية والعلمية والتكنولوجية. تضم الجامعة كليات الطب البشري، والعلاج الطبيعي، والصيدلة، والتكنولوجيا الحيوية، وتقدم برامجها باللغة الإنجليزية. وتركز الدراسة على الجمع بين الجانب الأكاديمي والتطبيق العملي، مع توفير معامل متخصصة وفرص للتدريب والبحث العلمي. كما تهتم الجامعة بالأنشطة الطلابية وتنمية المهارات، وتوفر بيئة تعليمية تهدف إلى إعداد الطلاب لمتطلبات سوق العمل.'
WHERE slug = 'merit-university';

UPDATE "University" SET description = 'The Arab Academy for Science, Technology and Maritime Transport is an educational institution affiliated with the League of Arab States. Founded in 1972, it offers study programs across a wide range of fields. Its specializations include engineering, computing and information technology, business administration, transport and logistics, and language and media, along with a number of medical and health programs and newer fields such as artificial intelligence. The Academy has branches in several Egyptian cities, including Alexandria, Cairo, El Alamein, Port Said and Aswan. Study combines academic education with practical application and training, with an emphasis on scientific research, innovation and international cooperation.',
  "descriptionAr" = 'الأكاديمية العربية للعلوم والتكنولوجيا والنقل البحري هي مؤسسة تعليمية تابعة لجامعة الدول العربية، تأسست عام 1972 وتقدم برامج دراسية في مجموعة واسعة من المجالات. تشمل تخصصاتها الهندسة، والحاسبات وتكنولوجيا المعلومات، وإدارة الأعمال، والنقل واللوجستيات، واللغة والإعلام، إلى جانب عدد من البرامج الطبية والصحية والتخصصات الحديثة مثل الذكاء الاصطناعي. وتنتشر فروع الأكاديمية في عدد من المدن المصرية، من بينها الإسكندرية والقاهرة والعلمين وبورسعيد وأسوان. وتركز الدراسة على الجمع بين التعليم الأكاديمي والتطبيق العملي والتدريب، مع الاهتمام بالبحث العلمي والابتكار والتعاون الدولي.'
WHERE slug = 'arab-academy-for-science-technology-and-maritime-transport';

UPDATE "University" SET description = 'October University for Modern Sciences and Arts (MSA) is a private university founded in 1996 in 6th of October City. It offers academic programs across a range of fields, including dentistry, pharmacy, biotechnology, engineering, computer science, management sciences, languages and translation, mass communication, arts and design, nutrition and food technology, and physical therapy. Study combines British academic standards with the requirements of university education in Egypt, with a focus on practical application and on developing research, analysis and problem-solving skills. The university also has academic partnerships with British universities and provides a learning environment with labs, training facilities and a variety of student activities.',
  "descriptionAr" = 'جامعة أكتوبر للعلوم الحديثة والآداب هي جامعة خاصة تأسست عام 1996 وتقع في مدينة 6 أكتوبر. تقدم الجامعة برامج أكاديمية في مجالات متنوعة تشمل طب الأسنان، والصيدلة، والتكنولوجيا الحيوية، والهندسة، وعلوم الحاسب، وعلوم الإدارة، واللغات والترجمة، والإعلام، والفنون والتصميم، والتغذية وتكنولوجيا الغذاء، والعلاج الطبيعي. وتعتمد الدراسة على الجمع بين المعايير الأكاديمية البريطانية ومتطلبات التعليم الجامعي في مصر، مع التركيز على التطبيق العملي وتنمية مهارات البحث والتحليل وحل المشكلات. كما ترتبط الجامعة بشراكات أكاديمية مع جامعات بريطانية، وتوفر بيئة تعليمية تضم معامل ومرافق تدريبية وأنشطة طلابية متنوعة.'
WHERE slug = 'msa-university';

UPDATE "University" SET description = 'The French University of Egypt is a national university founded in 2002 in El Shorouk City, offering an educational model that combines Egyptian and French education. Its programs cover engineering, artificial intelligence and data science, cybersecurity, information systems, business administration, economics, applied languages, architecture and more. Teaching is in English and French with support for Arabic, through academic partnerships with a number of French universities. Some of its programs also lead to accredited French degrees, along with opportunities for exchange and study in France, with a focus on practical application and scientific research.',
  "descriptionAr" = 'الجامعة الفرنسية في مصر هي جامعة أهلية تأسست عام 2002 وتقع في مدينة الشروق، وتقدم نموذجا تعليميا يجمع بين التعليم المصري والفرنسي. تضم الجامعة برامج في مجالات الهندسة، والذكاء الاصطناعي وعلوم البيانات، والأمن السيبراني، ونظم المعلومات، وإدارة الأعمال، والاقتصاد، واللغات التطبيقية، والعمارة وغيرها. وتقدم الدراسة باللغتين الإنجليزية والفرنسية مع دعم للغة العربية، من خلال شراكات أكاديمية مع عدد من الجامعات الفرنسية. كما تتيح بعض برامجها الحصول على درجات فرنسية معتمدة، إلى جانب فرص للتبادل والدراسة في فرنسا، مع التركيز على التطبيق العملي والبحث العلمي.'
WHERE slug = 'universite-francaise-degypte';

UPDATE "University" SET description = 'Badr University in Cairo is a private university founded in 2010 in Badr City, Cairo Governorate. It offers a wide variety of academic programs in fields including medicine, dentistry, pharmacy, engineering and technology, physical therapy, nursing, business administration, languages and translation, arts, humanities and more. Study follows the credit-hour system, with a focus on practical application, training and skills development. The campus offers labs, learning facilities and a range of student services, alongside sports, cultural and artistic activities. The university also provides fully equipped housing for female students with round-the-clock security and support, as well as transportation linking the university to a number of areas.',
  "descriptionAr" = 'جامعة بدر بالقاهرة هي جامعة خاصة تأسست عام 2010 وتقع في مدينة بدر بمحافظة القاهرة. تقدم الجامعة برامج أكاديمية متنوعة في مجالات تشمل الطب، وطب الفم والأسنان، والصيدلة، والهندسة والتكنولوجيا، والعلاج الطبيعي، والتمريض، وإدارة الأعمال، واللغات والترجمة، والفنون، والعلوم الإنسانية وغيرها. وتعتمد الدراسة على نظام الساعات المعتمدة، مع التركيز على التطبيق العملي والتدريب وتنمية المهارات. كما يوفر الحرم الجامعي معامل ومرافق تعليمية وخدمات طلابية متنوعة، إلى جانب أنشطة رياضية وثقافية وفنية. وتوفر الجامعة سكنا مجهزا للطالبات مع خدمات أمن ودعم على مدار الساعة، بالإضافة إلى وسائل نقل تربط الجامعة بعدد من المناطق.'
WHERE slug = 'badr-university-in-cairo';

UPDATE "University" SET description = 'Sphinx University is a private university established by presidential decree in 2019 in New Assiut City. It offers programs across a range of fields, including dentistry, pharmacy, physical therapy, veterinary medicine, engineering, computing and artificial intelligence, applied health sciences, and nursing. Study combines academic and applied curricula, with programs running from bachelor''s level through to postgraduate studies. The Faculty of Engineering includes specializations such as architecture, civil engineering, communications and electronics, and mechanical engineering, while health sciences include specializations such as medical laboratories, radiology, and emergency and critical care.',
  "descriptionAr" = 'جامعة سفنكس هي جامعة خاصة تأسست بقرار جمهوري عام 2019 وتقع في مدينة أسيوط الجديدة. تقدم الجامعة برامج دراسية في مجالات متنوعة تشمل طب الفم والأسنان، والصيدلة، والعلاج الطبيعي، والطب البيطري، والهندسة، والحاسبات والذكاء الاصطناعي، والعلوم الصحية التطبيقية، والتمريض. وتعتمد الدراسة على الجمع بين المناهج الأكاديمية والتطبيقية، مع برامج تمتد من مرحلة البكالوريوس إلى الدراسات العليا. وتضم كلية الهندسة تخصصات مثل الهندسة المعمارية والمدنية والاتصالات والإلكترونيات والهندسة الميكانيكية، بينما تشمل العلوم الصحية تخصصات مثل المختبرات الطبية والأشعة والطوارئ والرعاية الحرجة.'
WHERE slug = 'sphinx-university';

UPDATE "University" SET description = 'The British University in Egypt is a private university founded in 2005 in El Shorouk City, Cairo. It offers English-taught programs following British teaching methods, through academic partnerships with British universities. Its specializations span engineering, computer science, business administration, economics and political science, mass communication, law, pharmacy, dentistry, nursing, arts and design, and more. Study is built on continuous assessment and practical application, with modern labs, lecture halls and learning facilities. The university also provides student housing and transportation services, along with scholarships and discounts for high-achieving and outstanding students.',
  "descriptionAr" = 'الجامعة البريطانية في مصر هي جامعة خاصة تأسست عام 2005 وتقع في مدينة الشروق بالقاهرة، وتقدم برامج دراسية باللغة الإنجليزية وفق أساليب تعليمية بريطانية، من خلال شراكات أكاديمية مع جامعات بريطانية. تضم الجامعة تخصصات في مجالات الهندسة، وعلوم الحاسب، وإدارة الأعمال، والاقتصاد والعلوم السياسية، والإعلام، والقانون، والصيدلة، وطب الأسنان، والتمريض، والفنون والتصميم وغيرها. وتركز الدراسة على التقييم المستمر والتطبيق العملي، مع توفير معامل وقاعات وتجهيزات تعليمية حديثة. كما توفر الجامعة سكنا طلابيا وخدمات للنقل، إلى جانب فرص للمنح والخصومات للطلاب المتفوقين والمتميزين.'
WHERE slug = 'british-university-in-egypt';

UPDATE "University" SET description = 'Future University in Egypt is a private university founded in 2006 in the Fifth Settlement, New Cairo. It has six faculties: dentistry; pharmacy; engineering and technology; computers and information technology; commerce and business administration; and economics and political science. The university focuses on teaching, scientific research and practical application, with specialized labs and facilities, including a dental hospital and an industrial training plant for pharmacy. It also has academic partnerships with international universities, and offers students sports, cultural and artistic activities, along with student clubs and training and career services.',
  "descriptionAr" = 'جامعة المستقبل في مصر هي جامعة خاصة تأسست عام 2006 وتقع في التجمع الخامس بالقاهرة الجديدة. تضم الجامعة ست كليات في مجالات طب الفم والأسنان، والصيدلة، والهندسة والتكنولوجيا، والحاسبات وتكنولوجيا المعلومات، والتجارة وإدارة الأعمال، والاقتصاد والعلوم السياسية. وتركز الجامعة على التعليم والبحث العلمي والتطبيق العملي، مع توفير معامل ومرافق متخصصة، منها مستشفى طب الأسنان ومصنع للتدريب الصناعي في مجال الصيدلة. كما ترتبط الجامعة بشراكات أكاديمية مع جامعات دولية، وتوفر للطلاب أنشطة رياضية وثقافية وفنية، إلى جانب الأندية الطلابية وخدمات التدريب والتوظيف.'
WHERE slug = 'future-university-in-egypt';

UPDATE "University" SET description = 'Misr International University is a private university founded in 1996 on the Cairo-Ismailia Desert Road. Teaching began with two faculties, Al-Alsun and Mass Communication, and Business Administration, before expanding to include engineering, pharmacy, computer science and dentistry, along with departments of architecture and of electronics and communications. The university focuses on integrating its academic programs with applied scientific research and student skills development, with an emphasis on innovation, entrepreneurship and professional development. It also has academic cooperation with international universities and institutions, and offers students a range of educational and community activities and services.',
  "descriptionAr" = 'جامعة مصر الدولية هي جامعة خاصة تأسست عام 1996 وتقع على طريق القاهرة – الإسماعيلية الصحراوي. بدأت الدراسة بكليتي الألسن والإعلام وإدارة الأعمال، ثم توسعت لتشمل الهندسة، والصيدلة، وعلوم الحاسب، وطب الفم والأسنان، إلى جانب أقسام الهندسة المعمارية والإلكترونيات والاتصالات. وتركز الجامعة على دمج البرامج التعليمية مع البحث العلمي التطبيقي وتنمية مهارات الطلاب، مع اهتمام بالابتكار وريادة الأعمال والتطوير المهني. كما ترتبط الجامعة بتعاون أكاديمي مع جامعات ومؤسسات دولية، وتوفر للطلاب أنشطة وخدمات تعليمية ومجتمعية متنوعة.'
WHERE slug = 'misr-international-university-miu';

UPDATE "University" SET description = 'Misr University for Science and Technology is a private university founded in 1996 in 6th of October City. It stands out for its fully integrated campus, which includes Souad Kafafi University Hospital, giving students in medical fields opportunities for hands-on training, as well as a central library, a testing center, sports facilities and an opera house. The university also provides transportation for students, and separate university housing for male and female students about 5 minutes from campus, with furnished rooms and apartments, supervision and round-the-clock medical services. The university also invests in student life through clubs, activities and a variety of events.',
  "descriptionAr" = 'جامعة مصر للعلوم والتكنولوجيا هي جامعة خاصة تأسست عام 1996 وتقع في مدينة السادس من أكتوبر. تتميز بتوفير بيئة جامعية متكاملة تضم مستشفى سعاد كفافي الجامعي، الذي يتيح لطلاب التخصصات الطبية فرصا للتدريب العملي، إلى جانب مكتبة مركزية ومركز اختبارات ومرافق رياضية ودار أوبرا. كما توفر الجامعة وسائل نقل للطلاب، وسكنا جامعيا منفصلا للطلاب والطالبات يبعد نحو 5 دقائق عن الحرم، مع غرف وشقق مفروشة وإشراف وخدمات طبية على مدار الساعة. وتهتم الجامعة بالحياة الطلابية من خلال الأندية والأنشطة والفعاليات المختلفة.'
WHERE slug = 'misr-university-for-science-and-technology';

UPDATE "University" SET description = 'Nile University is a non-profit national university founded in 2006, and one of the universities with a particular focus on scientific research, innovation and entrepreneurship. The university relies on applied learning through real projects and hands-on training in collaboration with more than 200 industry partners. It also has specialized research centers in technology, engineering and computer science, along with a system that supports students in developing ideas and turning them into projects and startups. The university also offers full and partial scholarships based on academic excellence and merit.',
  "descriptionAr" = 'جامعة النيل هي جامعة أهلية غير هادفة للربح تأسست عام 2006، وتعد من الجامعات التي تركز بشكل خاص على البحث العلمي والابتكار وريادة الأعمال. تعتمد الجامعة على التعلم التطبيقي من خلال مشروعات حقيقية وتدريب عملي بالتعاون مع أكثر من 200 شريك من قطاع الصناعة. كما توفر مراكز بحثية متخصصة في مجالات التكنولوجيا والهندسة وعلوم الحاسب، إلى جانب منظومة لدعم الطلاب في تطوير الأفكار وتحويلها إلى مشروعات وشركات ناشئة. وتقدم الجامعة أيضا منحا دراسية كاملة وجزئية للطلاب وفقا لمعايير التفوق والاستحقاق.'
WHERE slug = 'nile-university';

UPDATE "University" SET description = 'October 6 University is Egypt''s first private university, founded in 1996 in 6th of October City. It stands out for its fully integrated campus, which includes a 320-bed teaching and treatment hospital, along with a central library and a range of student centers and services. The university provides student housing for men and women: women''s housing is on campus and men''s housing is near the university, with single and double rooms and living and internet services. It also runs transportation covering different parts of Greater Cairo, as well as sports fields and many student activities.',
  "descriptionAr" = 'جامعة 6 أكتوبر هي أول جامعة خاصة في مصر، تأسست عام 1996 وتقع في مدينة 6 أكتوبر. تتميز بحرم جامعي متكامل يضم مستشفى تعليمي وعلاجي بسعة 320 سريرا، إلى جانب مكتبة مركزية ومراكز وخدمات طلابية متنوعة. كما توفر الجامعة سكنًا طلابيًا للطلاب والطالبات، حيث يقع سكن الطالبات داخل الحرم الجامعي وسكن الطلاب بالقرب من الجامعة، مع غرف فردية ومزدوجة وخدمات للمعيشة والإنترنت. وتوفر الجامعة أيضا خدمات نقل تغطي مناطق مختلفة من القاهرة الكبرى، بالإضافة إلى ملاعب رياضية وأنشطة طلابية متعددة.'
WHERE slug = 'october-6-university';

UPDATE "University" SET description = 'Ahram Canadian University is a private university founded in 2005 in 6th of October City, offering students a university environment that combines academic study with practical application. The university has specialized labs and facilities that help students gain practical experience alongside their studies, with an emphasis on training and developing the skills the job market needs. It also offers a varied university life through student, sports and cultural activities, along with services that help students develop their skills and build experience outside the classroom. The university is affiliated with Al-Ahram Establishment, providing a learning environment that brings together study, training and connections with a range of professional fields.',
  "descriptionAr" = 'جامعة الأهرام الكندية هي جامعة خاصة تأسست عام 2005 في مدينة 6 أكتوبر، وتوفر للطلاب بيئة جامعية تجمع بين الدراسة الأكاديمية والتطبيق العملي. تتميز الجامعة بوجود معامل ومرافق متخصصة تساعد الطلاب على اكتساب الخبرة العملية إلى جانب الدراسة، مع الاهتمام بالتدريب وتنمية المهارات المطلوبة لسوق العمل. كما توفر حياة جامعية متنوعة من خلال الأنشطة الطلابية والرياضية والثقافية، إلى جانب خدمات تساعد الطلاب على تطوير مهاراتهم وبناء خبراتهم خارج قاعات الدراسة. وترتبط الجامعة بمؤسسة الأهرام، بما يوفر بيئة تعليمية تجمع بين الدراسة والتدريب والتواصل مع مجالات مهنية متنوعة.'
WHERE slug = 'ahram-canadian-university';

UPDATE "University" SET description = 'Al Hayah University is a private university established by presidential decree in 2019 in the universities district of the Fifth Settlement. Its campus covers 32 feddans (about 33 acres) and houses learning facilities and equipped labs, including specialized physical therapy labs and modern information technology labs. The university focuses on education that combines study with practical application, with an emphasis on scientific research and cooperation with foreign universities. It also aims to produce graduates with the skills to compete in the job market in Egypt and abroad, and provides a modern university environment in the New Cairo universities district.',
  "descriptionAr" = 'جامعة الحياة هي جامعة خاصة تأسست بقرار جمهوري عام 2019 وتقع في منطقة الجامعات بالتجمع الخامس. تمتد على مساحة 32 فدانا وتضم مرافق تعليمية ومعامل مجهزة، من بينها معامل متخصصة للعلاج الطبيعي ومعامل حديثة لتكنولوجيا المعلومات. وتركز الجامعة على تقديم تعليم يجمع بين الدراسة والتطبيق العملي، مع اهتمام بالبحث العلمي والتعاون مع جامعات أجنبية. كما تسعى إلى إعداد خريجين يمتلكون المهارات التي تساعدهم على المنافسة في سوق العمل داخل مصر وخارجها، وتوفر بيئة جامعية حديثة في منطقة الجامعات بالقاهرة الجديدة.'
WHERE slug = 'al-hayah-university-in-cairo';

UPDATE "University" SET description = 'Al Salam University in Egypt is a private university in the heart of the Delta, in Gharbia Governorate, founded in 2018. The university focuses on combining academic excellence with practical application, providing a modern learning environment that supports students and prepares them for the job market. It offers a variety of scholarships for high achievers, including scholarships for top Thanaweya Amma students as well as academic and sports excellence scholarships. The university also provides student transportation and fully serviced hotel-style housing. Campus life includes a variety of activities and sports facilities, with opportunities to take part in competitions and student events.',
  "descriptionAr" = 'جامعة السلام بمصر هي جامعة خاصة تقع في قلب منطقة الدلتا بمحافظة الغربية، وتأسست عام 2018. تركز الجامعة على الجمع بين التميز الأكاديمي والتطبيق العملي، مع توفير بيئة تعليمية حديثة لدعم الطلاب وتأهيلهم لسوق العمل. وتتميز بتقديم منح دراسية متنوعة للمتفوقين، تشمل منحا لاوائل الثانوية العامة، إلى جانب منح التفوق الدراسي والرياضي. كما توفر الجامعة خدمة الانتقالات للطلاب، بالإضافة إلى سكن فندقي متكامل الخدمات. وتضم الحياة الجامعية أنشطة ومرافق رياضية متنوعة، مع فرص للمشاركة في المسابقات والفعاليات الطلابية.'
WHERE slug = 'al-salam-university';

UPDATE "University" SET description = 'Badya University offers a modern university experience focused on hands-on learning and student skills development, with advanced labs and equipment and learning spaces designed to support study and practice. The university also works to connect students with the job market through training opportunities and cooperation with companies, alongside a varied campus life that includes clubs and sports, artistic and social activities. It also provides services for students'' convenience, including transportation, making the study experience more complete.',
  "descriptionAr" = 'تتميز جامعة باديا بتقديم تجربة جامعية حديثة تركز على التعلم العملي وتنمية مهارات الطلاب، مع توفير معامل وتجهيزات متطورة ومساحات تعليمية مصممة لدعم الدراسة والتطبيق. كما تهتم الجامعة بربط الطلاب بسوق العمل من خلال فرص التدريب والتعاون مع الشركات، إلى جانب حياة جامعية متنوعة تشمل الأندية والأنشطة الرياضية والفنية والاجتماعية. وتوفر الجامعة كذلك خدمات تساعد على راحة الطلاب، من بينها خدمة الانتقالات، مما يجعل تجربة الدراسة أكثر تكاملا.'
WHERE slug = 'badya-university';

UPDATE "University" SET description = 'Canadian International College (CIC) offers education that combines academic study with practical application, with a partnership with Canada''s Cape Breton University that allows students to earn an accredited Canadian bachelor''s degree alongside the Egyptian degree in eligible programs. The college focuses on hands-on training and projects linked to the job market, with smart classrooms and modern labs on its New Cairo and Sheikh Zayed campuses. It also offers opportunities to study or go on exchange in Canada, along with a variety of student activities and clubs, including the Student Union, AIESEC and Hult Prize, giving students a university experience that brings together study, training and student life.',
  "descriptionAr" = 'تتميز الكلية الكندية الدولية (CIC) بتقديم تعليم يجمع بين الدراسة الأكاديمية والتطبيق العملي، مع شراكة مع جامعة كيب بريتون الكندية تتيح للطلاب الحصول على درجة بكالوريوس كندية معتمدة إلى جانب الدرجة المصرية في البرامج المتاحة. وتركز الكلية على التدريب العملي والمشروعات المرتبطة بسوق العمل، مع فصول ذكية ومعامل حديثة في حرمي القاهرة الجديدة والشيخ زايد. كما توفر فرصا للدراسة أو التبادل في كندا، إلى جانب أنشطة وأندية طلابية متنوعة تشمل اتحاد الطلاب وAIESEC وHult Prize، مما يمنح الطلاب تجربة جامعية تجمع بين الدراسة والتدريب والحياة الطلابية.'
WHERE slug = 'canadian-international-college';

UPDATE "University" SET description = 'City University in Cairo offers applied programs that aim to equip students with skills that match the needs of the job market, with an emphasis on scientific research and practical projects. The university is located in New Heliopolis City in Badr City, near the New Administrative Capital, and has research units in fields such as engineering and technology, medical sciences and biotechnology. It also offers scholarships for high-achieving students, and emphasizes training, cooperative education and linking study to the needs of different sectors. University life also offers activities and events that help students develop their skills and experience beyond their studies.',
  "descriptionAr" = 'تتميز جامعة المدينة بالقاهرة بتقديم برامج تعليمية تطبيقية تهدف إلى إعداد الطلاب بمهارات تتوافق مع احتياجات سوق العمل، مع الاهتمام بالبحث العلمي والمشروعات العملية. وتقع الجامعة في مدينة هليوبوليس الجديدة بمدينة بدر، بالقرب من العاصمة الإدارية الجديدة، وتضم وحدات بحثية في مجالات متنوعة مثل الهندسة والتكنولوجيا والعلوم الطبية والتكنولوجيا الحيوية. كما توفر الجامعة منحا دراسية للطلاب المتفوقين، وتهتم بالتدريب والتعليم التعاوني وربط الدراسة باحتياجات قطاعات العمل المختلفة. وتوفر الحياة الجامعية كذلك أنشطة وفعاليات تساعد الطلاب على تطوير مهاراتهم وتجاربهم خارج الدراسة.'
WHERE slug = 'city-university';

UPDATE "University" SET description = 'Coventry University Egypt offers a British education through its branch in the New Administrative Capital, with programs delivered under the supervision of the parent university in the UK and to the same academic standards. Study focuses on practical application and linking education to the needs of the job market, with notable specializations in computing, engineering, design, media and business administration. Its computing programs have specialized labs that include virtual reality technologies and cybersecurity systems, and students also have opportunities to benefit from Coventry University''s academic and research environment.',
  "descriptionAr" = 'جامعة كوفنتري في مصر تقدم تجربة تعليم بريطانية من خلال فرعها في العاصمة الإدارية الجديدة، مع برامج دراسية تُقدم تحت إشراف الجامعة الأم في بريطانيا وبنفس معاييرها الأكاديمية. تركز الدراسة على التطبيق العملي وربط التعليم باحتياجات سوق العمل، مع تخصصات مميزة في الحاسبات والهندسة والتصميم والإعلام وإدارة الأعمال. كما توفر برامج الحاسبات معامل متخصصة تشمل تقنيات الواقع الافتراضي وأنظمة الأمن السيبراني، إلى جانب فرص للطلاب للاستفادة من البيئة الأكاديمية والبحثية لجامعة كوفنتري.'
WHERE slug = 'coventry-university-egypt';

UPDATE "University" SET description = 'Deraya University in New Minya City offers a learning experience that combines academic study with practical application, with a focus on preparing students for the job market and developing their professional skills. The university provides labs, clinics and specialized facilities that help students apply what they learn, especially in medical and engineering fields. It also invests in campus life through sports, cultural and social activities, along with training opportunities and cooperation with various institutions and organizations. The university also offers student services including transportation, medical care and recreational facilities, for a well-rounded university experience.',
  "descriptionAr" = 'تتميز جامعة دراية بمدينة المنيا الجديدة بتقديم تجربة تعليمية تجمع بين الدراسة الأكاديمية والتطبيق العملي، مع التركيز على إعداد الطلاب لسوق العمل وتنمية مهاراتهم المهنية. وتوفر الجامعة معامل وعيادات ومرافق متخصصة تساعد الطلاب على تطبيق ما يتعلمونه، خاصة في المجالات الطبية والهندسية. كما تهتم بالحياة الجامعية من خلال الأنشطة الرياضية والثقافية والاجتماعية، إلى جانب فرص التدريب والتعاون مع مؤسسات وجهات مختلفة. وتوفر الجامعة كذلك خدمات للطلاب تشمل النقل والرعاية الطبية والمرافق الترفيهية، لتقديم تجربة جامعية متكاملة.'
WHERE slug = 'deraya-university';

UPDATE "University" SET description = 'The Egypt-Japan University of Science and Technology (E-JUST) offers a distinctive experience based on the Japanese approach to education, with a focus on projects, practical application, research and innovation. The campus has specialized labs and modern equipment that help students turn knowledge into real applications and projects. The university also provides on-campus student housing, along with sports fields and facilities and student activities and clubs. Its environment also offers opportunities for academic cooperation and exchange with Japanese and international universities and institutions, giving students a learning experience that goes beyond the lecture hall.',
  "descriptionAr" = 'الجامعة المصرية اليابانية للعلوم والتكنولوجيا (E-JUST) تقدم تجربة مختلفة تعتمد على أسلوب التعليم الياباني، مع التركيز على المشروعات والتطبيق العملي والبحث والابتكار. ويضم الحرم الجامعي معامل متخصصة وتجهيزات حديثة تساعد الطلاب على تحويل المعرفة إلى تطبيقات ومشروعات فعلية. كما توفر الجامعة سكنا طلابيا داخل الحرم، إلى جانب ملاعب ومرافق رياضية متنوعة وأنشطة وأندية طلابية. وتتيح بيئة الجامعة أيضا فرصا للتعاون والتبادل الأكاديمي مع جامعات ومؤسسات يابانية ودولية، مما يمنح الطلاب تجربة تعليمية تتجاوز الدراسة داخل المحاضرات.'
WHERE slug = 'egypt-japan-university-of-science-and-technology';

UPDATE "University" SET description = 'Egypt University of Informatics (EUI) offers a university experience specialized in technology and communications, on a modern campus in Knowledge City in the New Administrative Capital. Study focuses on practical application and innovation, with more than 100 internship opportunities with companies and organizations in the ICT sector. Qualified students can earn dual degrees in partnership with international universities, and outstanding students can receive full and partial scholarships. The university offers an active student life with more than 16 clubs and events, as well as furnished university housing and career services that help students prepare for the job market.',
  "descriptionAr" = 'جامعة مصر للمعلوماتية (EUI) تقدم تجربة جامعية متخصصة في مجالات التكنولوجيا والاتصالات، داخل حرم حديث في مدينة المعرفة بالعاصمة الإدارية الجديدة. وتركز الدراسة على التطبيق العملي والابتكار، مع أكثر من 100 فرصة تدريب مع شركات ومؤسسات من قطاع تكنولوجيا المعلومات والاتصالات. كما تتيح للطلاب المؤهلين فرص الحصول على شهادات مزدوجة بالتعاون مع جامعات دولية، إلى جانب منح دراسية كاملة وجزئية للطلاب المتميزين. وتوفر الجامعة حياة طلابية نشطة من خلال أكثر من 16 ناديا وفعالية، بالإضافة إلى سكن جامعي مفروش وخدمات مهنية تساعد الطلاب على الاستعداد لسوق العمل.'
WHERE slug = 'egyptian-informatics-university';

UPDATE "University" SET description = 'Galala University is a non-profit national university in Galala City, offering a modern university experience that combines applied education with research and innovation. It offers more than 60 programs across a range of specializations, with advanced labs and facilities that help students study, carry out projects and get hands-on training. It also stands out for its partnership with Arizona State University, which offers dual-degree programs in a number of specializations. The campus includes student housing and a variety of sports and recreational facilities, along with student clubs and activities, for a complete on-campus university experience, with transportation linking the university to Cairo and Giza.',
  "descriptionAr" = 'جامعة الجلالة هي جامعة أهلية غير هادفة للربح تقع في مدينة الجلالة، وتقدم تجربة جامعية حديثة تجمع بين التعليم التطبيقي والبحث والابتكار. تضم الجامعة أكثر من 60 برنامجا في تخصصات متنوعة، مع معامل ومرافق متطورة تساعد الطلاب على الدراسة وتنفيذ المشروعات والتدريب العملي. كما تتميز بشراكتها مع "Arizona State University" التي تتيح برامج درجات مزدوجة في عدد من التخصصات. ويضم الحرم الجامعي سكنا للطلاب ومرافق رياضية وترفيهية متنوعة، إلى جانب الأندية والأنشطة الطلابية، لتوفير تجربة جامعية متكاملة داخل الحرم، مع خدمات نقل تربط الجامعة بالقاهرة والجيزة.'
WHERE slug = 'galala-university';

UPDATE "University" SET description = 'Heliopolis University for Sustainable Development offers a distinctive learning experience focused on sustainable development and hands-on learning, combining teaching, scientific research and practical application. The campus has extensive green spaces and a variety of sports facilities, along with university housing, a medical center and a botanical garden. The university also offers the Core Program, which focuses on the humanities, languages and arts and on developing creativity and social responsibility. It gives students the chance to apply what they learn through projects and practical experiences linked to community needs, in a campus environment that cares about sustainability and protecting the environment.',
  "descriptionAr" = 'جامعة هليوبوليس للتنمية المستدامة تتميز بتجربة تعليمية مختلفة تركز على التنمية المستدامة والتعلم العملي، حيث تجمع الدراسة بين التعليم والبحث العلمي والتطبيق. ويضم الحرم الجامعي مساحات خضراء واسعة ومرافق رياضية متنوعة، إلى جانب السكن الجامعي والمركز الطبي والحديقة النباتية. كما تقدم الجامعة البرنامج الأساسي (Core Program) الذي يهتم بالعلوم الإنسانية واللغات والفنون وتنمية الإبداع والمسؤولية الاجتماعية. وتمنح الجامعة الطلاب فرصة لتطبيق ما يتعلمونه من خلال مشروعات وتجارب عملية مرتبطة باحتياجات المجتمع، مع بيئة جامعية تهتم بالاستدامة والحفاظ على البيئة.'
WHERE slug = 'heliopolis-university-for-sustainable-development';

UPDATE "University" SET description = 'Horus University in New Damietta combines study with practical application in a modern campus environment, offering a varied learning experience across medical, engineering, technology and management specializations. The university prepares students for the job market through labs and hands-on training, with particular attention to newer specializations such as artificial intelligence and informatics. It also provides digital services that make it easy for students to follow their registration, schedules, grades and course materials. Campus life includes a variety of activities and services, giving students an experience that brings together study, training and life on campus.',
  "descriptionAr" = 'جامعة تجمع بين الدراسة والتطبيق العملي في بيئة جامعية حديثة، فجامعة حورس في دمياط الجديدة توفر تجربة تعليمية متنوعة تضم تخصصات طبية وهندسية وتكنولوجية وإدارية. وتهتم الجامعة بتجهيز الطلاب لسوق العمل من خلال المعامل والتدريب العملي، مع اهتمام خاص بالتخصصات الحديثة مثل الذكاء الاصطناعي والمعلوماتية. كما توفر خدمات رقمية تساعد الطلاب في متابعة التسجيل والجداول والدرجات والمواد الدراسية بسهولة. وتضم الحياة الجامعية أنشطة وخدمات متنوعة، لتوفر للطلاب تجربة تجمع بين الدراسة والتدريب والحياة داخل الحرم الجامعي.'
WHERE slug = 'horus-university-in-egypt';

UPDATE "University" SET description = 'Innovation University is a private non-profit university in 10th of Ramadan City, offering a modern learning experience focused on innovation, practical application and entrepreneurship. It stands out for programs in technology, engineering, medical sciences, business administration, and arts and design, with a clear emphasis on linking study to the needs of the job market and cooperating with companies. The university also provides training opportunities and practical projects, and invests in scientific research, artificial intelligence and innovation. It also offers a range of scholarships and incentives for students who excel academically and in sports, and has a prime location opposite the electric train station and the bus station in 10th of Ramadan City.',
  "descriptionAr" = 'جامعة الابتكار هي جامعة خاصة غير هادفة للربح تقع في مدينة العاشر من رمضان، وتقدم تجربة تعليمية حديثة تركز على الابتكار والتطبيق العملي وريادة الأعمال. وتتميز ببرامج في مجالات التكنولوجيا والهندسة والعلوم الطبية وإدارة الأعمال والفنون والتصميم، مع اهتمام واضح بربط الدراسة باحتياجات سوق العمل والتعاون مع الشركات. كما توفر الجامعة فرصا للتدريب والمشروعات العملية، وتهتم بالبحث العلمي والذكاء الاصطناعي والابتكار. وتقدم أيضا مجموعة من المنح والحوافز للطلاب المتفوقين أكاديميا ورياضيا، مع موقع مميز أمام محطة القطار الكهربائي ومحطة الحافلات بمدينة العاشر من رمضان.'
WHERE slug = 'innovation-university';

UPDATE "University" SET description = 'King Salman International University is a non-profit national university offering a distinctive university experience in South Sinai through three branches in El Tor, Sharm El Sheikh and Ras Sedr. It stands out for its smart campus, with modern labs and classrooms that support hands-on learning and new specializations, and a focus on innovation and scientific research. Among its highlights is hotel-style housing on campus, along with restaurants, student services, sports facilities and swimming pools. The university also offers a varied student life through sports, cultural and recreational activities, making study a complete experience that combines education and campus life in a unique setting in South Sinai.',
  "descriptionAr" = 'جامعة الملك سلمان الدولية هي جامعة أهلية غير هادفة للربح تقدم تجربة جامعية مختلفة في جنوب سيناء من خلال ثلاثة أفرع في الطور وشرم الشيخ ورأس سدر. وتتميز بحرم جامعي ذكي يضم معامل وفصولا حديثة تدعم التعلم العملي والتخصصات الحديثة، مع التركيز على الابتكار والبحث العلمي. ومن أبرز مميزاتها السكن الفندقي داخل الحرم، إلى جانب المطاعم والخدمات الطلابية والمرافق الرياضية وحمامات السباحة. كما توفر الجامعة حياة طلابية متنوعة من خلال الأنشطة الرياضية والثقافية والترفيهية، مما يجعل الدراسة تجربة متكاملة تجمع بين التعليم والحياة الجامعية في بيئة مميزة بجنوب سيناء.'
WHERE slug = 'king-salman-international-university';

UPDATE "University" SET description = 'Lotus University in Minya is a private university in New Minya City, offering a modern university experience focused on innovation, hands-on learning and preparing students for the job market. The university offers a variety of specializations, with modern labs and equipment and opportunities for research and practical application. Its campus includes student housing, green spaces, sports fields and restaurants, along with sports, cultural and social activities that help students build relationships and develop their skills beyond their studies. The university uses the credit-hour system, in a learning environment that values innovation, social responsibility and serving the community of Upper Egypt.',
  "descriptionAr" = 'جامعة اللوتس بالمنيا هي جامعة خاصة تقع في مدينة المنيا الجديدة، وتقدم تجربة جامعية حديثة تركز على الابتكار والتعلم العملي وتأهيل الطلاب لسوق العمل. وتوفر الجامعة مجموعة متنوعة من التخصصات، مع معامل وتجهيزات حديثة وفرص للبحث والتطبيق العملي. كما تتميز بحرم جامعي يضم سكنًا للطلاب، ومساحات خضراء، وملاعب، ومطاعم، إلى جانب أنشطة رياضية وثقافية واجتماعية تساعد الطلاب على تكوين علاقات وتطوير مهاراتهم خارج الدراسة. وتستخدم الجامعة نظام الساعات المعتمدة، مع بيئة تعليمية تهتم بالابتكار والمسؤولية الاجتماعية وخدمة مجتمع صعيد مصر.'
WHERE slug = 'lotus-university';

UPDATE "University" SET description = 'Modern University for Technology and Information (MTI) is a private university in Mokattam, offering a learning environment that combines academic study with practical application. The university has a 175-bed teaching university hospital, along with 22 outpatient clinics, labs, a radiology department, operating rooms and an intensive care unit, giving medical students the chance to train in a fully integrated medical setting. It also has specialized technology and training labs and centers, and offers courses in areas such as artificial intelligence, programming and information technology. MTI also invests in student life through scientific, cultural, artistic and sports activities and training opportunities linked to the job market.',
  "descriptionAr" = 'الجامعة الحديثة للتكنولوجيا والمعلومات (MTI) هي جامعة خاصة في المقطم، وتتميز بتوفير بيئة تعليمية تجمع بين الدراسة الأكاديمية والتطبيق العملي. وتضم الجامعة مستشفى جامعي تعليمي بسعة 175 سريرا، إلى جانب 22 عيادة خارجية ومعامل وقسم أشعة وغرف عمليات ووحدة عناية مركزة، مما يوفر لطلاب الطب فرصة للتدريب العملي داخل بيئة طبية متكاملة. كما تضم الجامعة معامل ومراكز متخصصة في التكنولوجيا والتدريب، وتوفر دورات في مجالات مثل الذكاء الاصطناعي والبرمجة وتكنولوجيا المعلومات. وتهتم MTI كذلك بالحياة الطلابية من خلال الأنشطة العلمية والثقافية والفنية والرياضية وفرص التدريب المرتبطة بسوق العمل.'
WHERE slug = 'modern-university-for-technology-and-information';

UPDATE "University" SET description = 'Nahda University is the first private university in Upper Egypt, located in New Beni Suef City on the Cairo-Beni Suef road. It offers a university experience that combines academic study with practical application, with a variety of specializations in medical, engineering, technology, management and arts fields. Among its highlights is Nahda University Hospital, which provides a training environment for medical students, along with labs, learning equipment and a center for scientific and applied research. The university also provides equipped, air-conditioned student housing with restaurants, a cafeteria, and security and cleaning services, as well as sports fields, sports, cultural and artistic activities, and transportation linking the university to Cairo and several surrounding governorates and cities.',
  "descriptionAr" = 'جامعة النهضة هي أول جامعة خاصة في صعيد مصر، وتقع في مدينة بني سويف الجديدة على طريق القاهرة–بني سويف. وتقدم تجربة جامعية تجمع بين الدراسة الأكاديمية والتطبيق العملي، مع تخصصات متنوعة في المجالات الطبية والهندسية والتكنولوجية والإدارية والفنية. ومن أبرز مميزاتها مستشفى جامعة النهضة التي توفر بيئة تدريبية لطلاب القطاع الطبي، إلى جانب معامل وتجهيزات تعليمية ومركز للأبحاث العلمية والتطبيقية. كما توفر الجامعة سكنًا طلابيًا مجهزًا ومكيفًا مع مطاعم وكافيتريا وخدمات أمن ونظافة، بالإضافة إلى ملاعب وأنشطة رياضية وثقافية وفنية وخدمات انتقال تربط الجامعة بالقاهرة وعدد من المحافظات والمدن المحيطة.'
WHERE slug = 'nahda-university';

UPDATE "University" SET description = 'New Alamein International University is a non-profit national university in New Alamein City, offering a modern university experience based on interdisciplinary education, project-based learning and practical application. It benefits from its location in New Alamein City, with a modern campus that includes advanced labs and learning and sports facilities, as well as on-campus student housing. The university also offers a variety of student activities and opportunities for training and cooperation with different institutions and companies, with a clear emphasis on innovation and scientific research. The nature of the campus and the city gives students the chance to enjoy a modern university environment that brings together study and student life.',
  "descriptionAr" = 'جامعة العلمين الدولية هي جامعة أهلية غير هادفة للربح تقع في مدينة العلمين الجديدة، وتقدم تجربة جامعية حديثة تعتمد على التعليم متعدد التخصصات والتعلم القائم على المشروعات والتطبيق العملي. وتتميز بموقعها داخل مدينة العلمين الجديدة، مع حرم جامعي حديث يضم معامل ومرافق تعليمية ورياضية متطورة، بالإضافة إلى سكن طلابي داخل الحرم. كما توفر الجامعة أنشطة طلابية متنوعة وفرصا للتدريب والتعاون مع مؤسسات وشركات مختلفة، مع اهتمام واضح بالابتكار والبحث العلمي. وتمنح طبيعة الحرم والمدينة الطلاب فرصة للاستفادة من بيئة جامعية حديثة تجمع بين الدراسة والحياة الطلابية.'
WHERE slug = 'new-alamein-international-university';

UPDATE "University" SET description = 'New Mansoura University is a non-profit national university in New Mansoura City, offering a modern learning experience based on project-based learning and practical application, with programs in a variety of fields suited to the needs of the job market. The campus has a modern design and includes specialized labs, a university hospital, and advanced learning and sports facilities. The university also provides on-campus student housing, along with restaurants, student services, sports fields and activity areas. It values innovation, scientific research and training, providing a campus environment that helps students combine study and student life in one place.',
  "descriptionAr" = 'جامعة المنصورة الجديدة هي جامعة أهلية غير هادفة للربح، تقع في مدينة المنصورة الجديدة، وتقدم تجربة تعليمية حديثة تعتمد على التعلم القائم على المشروعات والتطبيق العملي، مع برامج في مجالات متنوعة تلائم احتياجات سوق العمل. يتميز الحرم الجامعي بتصميم حديث ويضم معامل متخصصة، مستشفى جامعي، ومرافق تعليمية ورياضية متطورة. كما توفر الجامعة سكنًا طلابيًا داخل الحرم، إلى جانب مطاعم وخدمات طلابية وملاعب ومناطق للأنشطة. وتهتم الجامعة بالابتكار والبحث العلمي والتدريب، مع توفير بيئة جامعية تساعد الطلاب على الجمع بين الدراسة والحياة الطلابية في مكان واحد.'
WHERE slug = 'new-mansoura-university';

UPDATE "University" SET description = 'Nile Valley University is a new private university in Fayoum Governorate, offering a learning experience focused on preparing students for the job market through modern curricula and labs equipped with advanced teaching and research methods. The university focuses on medical and technology fields, with specializations such as dentistry, pharmacy, applied health sciences and nursing, as well as physical therapy and artificial intelligence. It also offers services that make university life easier, including transportation, on-campus internet and dedicated parking. The university also values scientific research, innovation and community partnerships, and is working towards becoming a smart campus.',
  "descriptionAr" = 'جامعة وادي النيل هي جامعة خاصة حديثة في محافظة الفيوم، وتقدم تجربة تعليمية تركز على إعداد الطلاب لسوق العمل من خلال مناهج حديثة ومعامل مجهزة بأساليب تدريس وبحث متطورة. وتتميز الجامعة بتركيزها على المجالات الطبية والتكنولوجية، مع تخصصات مثل طب الأسنان والصيدلة والعلوم الصحية التطبيقية والتمريض، إلى جانب العلاج الطبيعي والذكاء الاصطناعي. كما توفر للطلاب خدمات تساعد على سهولة الحياة الجامعية، منها خدمة النقل، الإنترنت داخل الحرم ومواقف مخصصة للسيارات. وتهتم الجامعة كذلك بالبحث العلمي والابتكار والشراكات المجتمعية، مع توجه لتحويل الحرم إلى جامعة ذكية.'
WHERE slug = 'nile-valley-university';

UPDATE "University" SET description = 'Obour University of Science and Technology (OUST) is a new university on the Cairo-Belbeis Desert Road, focused on practical education linked to the needs of the job market. It currently has faculties of pharmacy, engineering and technology, computing and artificial intelligence, and business administration and entrepreneurship, with programs aimed at modern, in-demand fields. The university emphasizes hands-on training through workshops and training programs with companies and institutions, and supports scientific research by establishing specialized research centers. It is also developing its digital services and an online student portal, with a clear focus on campus life and engaging with students.',
  "descriptionAr" = 'جامعة العبور للعلوم والتكنولوجيا (OUST) هي جامعة حديثة تقع على طريق القاهرة–بلبيس الصحراوي، وتركز على تقديم تعليم عملي يرتبط باحتياجات سوق العمل. وتضم حاليا كليات الصيدلة والهندسة والتكنولوجيا والحاسبات والذكاء الاصطناعي وإدارة الأعمال وريادة الأعمال، مع برامج تستهدف المجالات الحديثة والتخصصات المطلوبة. وتهتم الجامعة بالتدريب العملي من خلال ورش وبرامج تدريبية بالتعاون مع الشركات والمؤسسات، إلى جانب دعم البحث العلمي وإنشاء مراكز بحثية متخصصة. كما تعمل الجامعة على تطوير خدماتها الرقمية وتوفير بوابة إلكترونية للطلاب، مع اهتمام واضح بالحياة الجامعية والتفاعل مع الطلاب.'
WHERE slug = 'obour-university-of-science-and-technology';

UPDATE "University" SET description = 'Pharos University in Alexandria is a private university in Alexandria, offering a learning experience that combines academic study with practical application, with a clear emphasis on training and preparing students for the job market. Among its highlights is Pharos University Hospital, which provides a training environment for students in medical fields, along with specialized clinics and labs. The university also has a training and consultancy center, sports and recreational facilities, and a variety of student activities that help students develop their skills beyond their studies. It also provides transportation and housing for students, making the study experience more complete.',
  "descriptionAr" = 'جامعة فاروس بالإسكندرية هي جامعة خاصة تقع في الإسكندرية، وتقدم تجربة تعليمية تجمع بين الدراسة الأكاديمية والتطبيق العملي، مع اهتمام واضح بالتدريب وتأهيل الطلاب لسوق العمل. ومن أبرز مميزاتها مستشفى فاروس الجامعي الذي يوفر بيئة تدريبية لطلاب التخصصات الطبية، إلى جانب عيادات ومعامل متخصصة. كما تضم الجامعة مركزا للتدريب والاستشارات، ومرافق رياضية وترفيهية، وأنشطة طلابية متنوعة تساعد على تطوير مهارات الطلاب خارج الدراسة. وتوفر الجامعة كذلك خدمات للنقل والسكن للطلاب، مما يجعل تجربة الدراسة أكثر تكاملا.'
WHERE slug = 'pharos-university-in-alexandria';

UPDATE "University" SET description = 'Rashid University is a private non-profit university in New Rashid City, Beheira Governorate, focused on education linked to the needs of the job market and to development in the region. The university offers specializations in fields such as physical therapy, nursing and business administration, with an emphasis on hands-on training and scientific research. It also aims to prepare specialized professionals able to meet the needs of different sectors, while providing students with a modern university environment.',
  "descriptionAr" = 'جامعة رشيد هي جامعة خاصة غير هادفة للربح تقع في مدينة رشيد الجديدة بمحافظة البحيرة، وتركز على تقديم تعليم يرتبط باحتياجات سوق العمل والتنمية في المنطقة. وتوفر الجامعة تخصصات في مجالات مثل العلاج الطبيعي والتمريض وإدارة الأعمال، مع اهتمام بالتدريب العملي والبحث العلمي. كما تستهدف إعداد كوادر متخصصة قادرة على تلبية احتياجات القطاعات المختلفة، مع توفير بيئة جامعية حديثة للطلاب.'
WHERE slug = 'rashid-university';

UPDATE "University" SET description = 'Ryada University for Science and Technology is a private university in Sadat City, offering a learning experience focused on practical application and linking study to the needs of the job market. The university has specializations in medical fields, engineering, computing and artificial intelligence, and business administration, with labs and equipment that help students gain practical experience. It also values student and sports activities, and provides a modern campus environment that helps students develop their skills alongside their studies. The university places particular emphasis on training, scientific research and entrepreneurship, helping students prepare for their professional lives.',
  "descriptionAr" = 'جامعة الريادة للعلوم والتكنولوجيا هي جامعة خاصة تقع في مدينة السادات، وتقدم تجربة تعليمية تركز على التطبيق العملي وربط الدراسة باحتياجات سوق العمل. تضم الجامعة تخصصات في المجالات الطبية والهندسية والحاسبات والذكاء الاصطناعي وإدارة الأعمال، مع معامل وتجهيزات تساعد الطلاب على اكتساب الخبرة العملية. كما تهتم الجامعة بالأنشطة الطلابية والرياضية، وتوفر بيئة جامعية حديثة تساعد الطلاب على تطوير مهاراتهم إلى جانب الدراسة. وتمنح الجامعة اهتماما خاصا بالتدريب والبحث العلمي وريادة الأعمال، بما يساعد الطلاب على الاستعداد للحياة المهنية.'
WHERE slug = 'ryada-university-for-science-and-technology';

UPDATE "University" SET description = 'Sinai University is a private university with two branches, in Arish and in El Qantara East in Ismailia Governorate, offering a learning experience focused on applied study and scientific research using the latest teaching methods and technologies. The Qantara branch has faculties of dentistry, pharmacy, engineering, information technology and computer science, mass communication, business administration and physical therapy, with ongoing development of its programs to match the needs of the job market. The university also has a center for scientific research and sustainable development, with units for central labs, research projects and training, and offers postgraduate programs including diplomas, master''s and doctoral degrees. It also stands out for teaching in English and for supporting international academic and research cooperation.',
  "descriptionAr" = 'جامعة سيناء هي جامعة خاصة لها فرعان في العريش والقنطرة شرق بمحافظة الإسماعيلية، وتقدم تجربة تعليمية تركز على الدراسة التطبيقية والبحث العلمي باستخدام أحدث أساليب وتقنيات التعليم. ويضم فرع القنطرة كليات طب الأسنان والصيدلة والهندسة وتكنولوجيا المعلومات وعلوم الحاسب والإعلام وإدارة الأعمال والعلاج الطبيعي، مع اهتمام بتطوير البرامج التعليمية بما يتوافق مع احتياجات سوق العمل. كما تضم الجامعة مركزا للبحث العلمي والتنمية المستدامة، ووحدات للمعامل المركزية والمشروعات البحثية والتدريب، وتوفر برامج للدراسات العليا تشمل الدبلوم والماجستير والدكتوراه. وتتميز الجامعة كذلك باستخدام اللغة الإنجليزية في التعليم، ودعم التعاون الأكاديمي والبحثي الدولي.'
WHERE slug = 'sinai-university';

UPDATE "University" SET description = 'University of East Capital is a private non-profit university in Mostakbal City, Haykestep, offering an educational model focused on linking study to the job market and practical application. The university has smart labs and classrooms and specialized training equipment, with a focus on medicine, dentistry, pharmacy, physical therapy, engineering, computing, business administration, mass communication, and arts and design. Among its key initiatives is a complex of teaching factories on campus, which lets students train in a real industrial environment and connect their projects to practical application. The university also invests in artificial intelligence, innovation and scientific research, and aims to turn student projects into applications and startups, while providing a modern campus environment that supports learning and professional development.',
  "descriptionAr" = 'جامعة شرق العاصمة هي جامعة خاصة غير هادفة للربح، تقع في مدينة المستقبل بالهايكستب، وتقدم نموذجا تعليميا يركز على ربط الدراسة بسوق العمل والتطبيق العملي. تتميز الجامعة بمعامل وقاعات ذكية وتجهيزات متخصصة للتدريب، مع تركيز على مجالات الطب وطب الأسنان والصيدلة والعلاج الطبيعي والهندسة والحاسبات وإدارة الأعمال والإعلام والفنون والتصميم. ومن أبرز توجهاتها إنشاء مجمع للمصانع التعليمية داخل الحرم يتيح للطلاب التدريب في بيئة صناعية حقيقية وربط المشروعات بالتطبيق العملي. كما تهتم الجامعة بالذكاء الاصطناعي والابتكار والبحث العلمي، وتسعى إلى تحويل مشروعات الطلاب إلى تطبيقات وشركات ناشئة، مع توفير بيئة جامعية حديثة تدعم التعلم والتطوير المهني.'
WHERE slug = 'university-of-east-capital';

UPDATE "University" SET description = 'The University of London gives students in Egypt the chance to earn a University of London degree through its recognized teaching center at the European Universities in Egypt (EUE) in the New Administrative Capital. Its programs cover a range of fields such as computer science, business administration, economics and finance, law, psychology, and politics and international relations, including programs under the academic direction of leading British institutions such as the London School of Economics (LSE). Students benefit from studying in Egypt while earning a qualification from the University of London, along with foundation programs that help them prepare for university study. Some programs also offer the chance to study locally while drawing on international academic resources and expertise.',
  "descriptionAr" = 'تتيح جامعة لندن للطلاب في مصر الحصول على درجة جامعية من جامعة لندن من خلال مركزها التعليمي المعتمد في الجامعات الأوروبية في مصر (EUE) بالعاصمة الإدارية الجديدة. وتتميز البرامج بتنوعها في مجالات مثل علوم الحاسب، إدارة الأعمال، الاقتصاد والتمويل، القانون، علم النفس والسياسة والعلاقات الدولية، مع وجود برامج ذات توجيه أكاديمي من مؤسسات بريطانية مرموقة مثل London School of Economics (LSE). ويستفيد الطلاب من الدراسة داخل مصر مع الحصول على مؤهل من جامعة لندن، إلى جانب برامج تأسيسية تساعد الطلاب على الاستعداد للدراسة الجامعية. كما توفر بعض البرامج فرصا للدراسة محليا مع إمكانية الاستفادة من الموارد والخبرة الأكاديمية الدولية.'
WHERE slug = 'university-of-london-egypt';

UPDATE "University" SET description = 'Zewail City of Science and Technology is a non-profit scientific and research institution that offers students a distinctive experience focused mainly on science, technology, research and innovation. Its University of Science and Technology offers specialized programs in engineering, science, pharmacy and medical sciences, with a strong reliance on research-based and project-based learning and lab work. The campus also stands out for its advanced research centers and labs, which let students take part in research projects in fields such as artificial intelligence, energy, water and biological sciences. The City also provides an academic environment that brings university study and scientific research together in one place, with opportunities for training and for taking part in conferences and research projects.',
  "descriptionAr" = 'مدينة زويل للعلوم والتكنولوجيا هي مؤسسة علمية وبحثية غير هادفة للربح، وتقدم للطلاب تجربة مختلفة تركز بشكل أساسي على العلوم والتكنولوجيا والبحث والابتكار. تضم جامعة العلوم والتكنولوجيا برامج متخصصة في الهندسة والعلوم والصيدلة والعلوم الطبية، مع اعتماد كبير على التعلم القائم على البحث والمشروعات والعمل داخل المعامل. كما يتميز الحرم بوجود مراكز ومعامل بحثية متقدمة تتيح للطلاب المشاركة في مشروعات بحثية في مجالات مثل الذكاء الاصطناعي والطاقة والمياه والعلوم الحيوية. وتوفر المدينة أيضا بيئة أكاديمية تجمع بين الدراسة الجامعية والبحث العلمي في مكان واحد، مع فرص للتدريب والمشاركة في المؤتمرات والمشروعات البحثية.'
WHERE slug = 'zewail-city-of-science-technology-and-innovation';

UPDATE "University" SET description = 'The German International University (GIU) operates according to the German higher education model and is located in the New Administrative Capital, with a strong focus on applied education and linking study to the needs of the job market. It offers specialized programs in engineering and robotics, informatics and computer science, business administration, biotechnology, pharmaceutical engineering, design, and physical therapy. Programs are taught in English, with strong academic ties to a number of German universities of applied sciences, and some programs offer opportunities for dual degrees and study in Germany. The university also stands out for its focus on scientific research and newer specializations, such as artificial intelligence, information and data security, logistics and digital design, along with scholarships for high-achieving students.',
  "descriptionAr" = 'الجامعة الألمانية الدولية (GIU) هي جامعة تعمل وفقا لنموذج التعليم العالي الألماني وتقع في العاصمة الإدارية الجديدة، وتتميز بتركيزها على التعليم التطبيقي وربط الدراسة باحتياجات سوق العمل. وتقدم برامج متخصصة في مجالات الهندسة والروبوتات، المعلوماتية وعلوم الحاسب، إدارة الأعمال، التكنولوجيا الحيوية، الهندسة الصيدلية، التصميم والعلاج الطبيعي. وتدرس البرامج باللغة الإنجليزية، مع ارتباط أكاديمي قوي بعدد من الجامعات الألمانية التطبيقية، كما تتيح بعض البرامج فرصا للحصول على درجات مزدوجة والدراسة في ألمانيا. وتتميز الجامعة كذلك باهتمامها بالبحث العلمي والتخصصات الحديثة، مثل الذكاء الاصطناعي وأمن المعلومات والبيانات واللوجستيات والتصميم الرقمي، مع وجود منح دراسية للطلاب المتفوقين.'
WHERE slug = 'german-international-university';

UPDATE "University" SET description = 'Memphis University is a private university in 6th of October City, focused on education that combines academic study with practical application, with an emphasis on preparing students for the job market. The university offers programs in fields such as medicine, dentistry, pharmacy, physical therapy, engineering, computing and artificial intelligence, business administration, mass communication, and arts and design. It also has specialized labs and training workshops that help students gain practical experience, along with a focus on scientific research and innovation. The university also offers student, sports and cultural activities, with on-campus services and facilities that support the student experience throughout their studies.',
  "descriptionAr" = 'جامعة ممفيس هي جامعة خاصة تقع في مدينة السادس من أكتوبر، وتركز على تقديم تعليم يجمع بين الدراسة الأكاديمية والتطبيق العملي، مع اهتمام بتأهيل الطلاب لسوق العمل. وتوفر الجامعة برامج في مجالات مثل الطب وطب الأسنان والصيدلة والعلاج الطبيعي والهندسة والحاسبات والذكاء الاصطناعي وإدارة الأعمال والإعلام والفنون والتصميم. كما تضم معامل وورش تدريب متخصصة تساعد الطلاب على اكتساب الخبرة العملية، إلى جانب الاهتمام بالبحث العلمي والابتكار. وتوفر الجامعة كذلك أنشطة طلابية ورياضية وثقافية، مع خدمات ومرافق داخل الحرم لدعم تجربة الطالب طوال فترة الدراسة.'
WHERE slug = 'memphis-university';

COMMIT;
